services:
  waywin-db:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    # environment:
    #   - PORT=3000
    #   - MONGO_URI=mongodb://waywin-db:27017
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - waywin-db

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - nodejs

networks:
  app-network:
    driver: bridge